---
- name: creating files or directories
  hosts: all
  become: true
  gather_facts: no

  tasks: 
  - name: create a file 
    file: 
      path: /opt/chaiwala
      state: touch 
      owner: rocky
      group: ansadmin
      mode: '0400'
