---
- name: cloning repo
  hosts: buildservers
  become: true
  gather_facts: no
  vars_files:
     - vault2.yml

  tasks:  
  - name: create a dir
    file:
      path: /opt/first_demo_project
      state: directory

  - name: cloning repo
    git: 
      repo: https://uvtechviraj:{{ git_password }}@github.com/uvtechviraj/first-demo-project.git
      dest: /opt/first_demo_project 
