--- 
- name: installing packages
  hosts: all
  become: true
  #  gather_facts: no 

  tasks:
  - name: installing httpd redhat 
    yum:
      name: httpd 
      state: installed 

  - copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html


  - name: start httpd services
    service: 
      name: httpd
      state: started 

