---
- name: Install Jenkins
  hosts: all
  become: true
  tasks:
    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present

    - name: Download Jenkins RPM package
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins-2.319.1-1.1.noarch.rpm
        dest: /tmp/jenkins.rpm

    - name: Install Java
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Install Jenkins RPM package
      yum:
        name: /tmp/jenkins.rpm
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes
        daemon_reload: yes
